VoltageVikingsApp/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('', views.landing_page_view),
                  path('account/', include('allauth.urls')),
                  path('captcha/', include('captcha.urls')),
                  path('home/', views.home_page),
                  path('getlocation/', views.get_location),
                  path('nearbystations/', views.nearby_stat),
                  path('route/<str:dest_lat>/<str:dest_long>/<int:id>/<int:page>/', views.map),
                  path(
                      'liverouting/<str:src_lat_got>/<str:src_long_got>/<str:dest_lat>/<str:dest_long>/<int:page>/',
                      views.live),
                  path('avail/', views.avail),
                  path('profile/', views.update_profile_profilepage),
                  path('completeprofile/', views.complete_profile),
                  path('nearbyhome/', views.nearby_home),
                  path('send_request/', views.send_request),
                  path('request_view/', views.req_view),
                  path('acc_req/', views.accept_request),
                  path('rej_req/', views.reject_request),
                  path('pay/<int:id>/', views.adv_payment),
                  path('advpaysuc/<int:id>/', views.advPaysucc),
                  path(
                      'homeroute/<str:src_lat>/<str:src_long>/<str:dest_lat>/<str:dest_long>/<int:id>/<int:page>/<int:txn_id>/',
                      views.maph),
                  path(
                      'liverouting/<str:src_lat_got>/<str:src_long_got>/<str:dest_lat>/<str:dest_long>/<int:page>/<int:txn_id>/',
                      views.live),
                  path('final_pay/<int:txn_id>/', views.final_payment),
                  path('finpaysuc/<int:id>/', views.finPaysucc),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

VoltagevikingsProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('VoltageVikingsApp.urls')),
    path('admin/', admin.site.urls),
]

VoltageVikingsApp/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    account_number = models.CharField(max_length=30, null=True, blank=True)
    bank_name = models.CharField(max_length=100, null=True, blank=True)
    ifsc_code = models.CharField(max_length=15, null=True, blank=True)
    branch = models.CharField(max_length=100, null=True, blank=True)
    upi_id = models.CharField(max_length=50, null=True, blank=True)
    home_address = models.CharField(max_length=200, null=True, blank=True)
    district = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=50, null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)
    zipcode = models.CharField(max_length=10, null=True, blank=True)
    lat = models.FloatField(max_length=120, null=True, blank=True)
    lon = models.FloatField(max_length=120, null=True, blank=True)
    available = models.BooleanField(default=False)
    got_loc = models.BooleanField(default=False)
    completed_profile = models.BooleanField(default=False)
    wallet = models.FloatField(max_length=120, blank=True, default=0.0)


class Requests(models.Model):
    from_user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='sent_requests')
    to_user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='received_requests')
    timestamp = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)
    charge_amt = models.FloatField(max_length=120, blank=True, null=True)
    charge_time = models.FloatField(max_length=120, blank=True, null=True)
    adv_pay_status = models.BooleanField(default=False)
    fin_pay_status = models.BooleanField(default=False)


class ChargingStations(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    lat = models.FloatField(max_length=120, null=True, blank=True)
    lon = models.FloatField(max_length=120, null=True, blank=True)

templates/main/completeprofile.html
{% extends 'base.html' %}

{% block toplink %}
<li class="nav__item">
    <a href="/account/logout" class="nav__link">Home</a>
</li>
<li class="nav__item">
    <a href="/home" class="nav__link">Logout</a>
</li>
{% endblock %}
{% block style %}
<style>
.container1 {
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f7f7f7;
    border: 1px solid purple;
    border-radius: 10px;
    margin-top:10%;
}

h1 {
    text-align: center;
    margin-top: 0;
    color: purple;
}

form {
    margin-top: 20px;
}

label, input {
    display: block;
    margin-bottom: 10px;
    width: 100%;
    color:black;
}
input {
    padding:10px;
    border: 1px solid purple;
    }
input[type="submit"] {
    background-color: #007bff;
    color: #fff;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

input[type="submit"]:hover {
    background-color: #0056b3;
}

#validation-msg {
    text-align: center;
    color: red;
    margin-top: 10px;
    font-size: 14px;
}

/* Media queries for responsive design */
@media screen and (max-width: 768px) {
    .container1 {
        max-width: 100%;
        margin: 0;
        padding: 10px;
        margin-top:20%;
    }
}

</style>
{% endblock %}
{% block content %}

<div class="container1" style="margin-top: 3cm;">
    <form method="post" action="/completeprofile/">
        {% csrf_token %}
        <h1 style="color:purple;">Complete your profile</h1>
        <h2 style="text-align:center;color:purple;">Note : Please enter the following information correctly if you
            have home station setup and be sure that your are in the location where exactly the port exists.</h2><br>
        <h3 style="text-align:center;color: purple;">Press skip and continue below to add details afterwards or not
            applicable</h3>
        <label class="my" id="skip" style="text-align:center;color:red;cursor:pointer;margin:10px;"
               onclick="window.location.href='/home';">Skip and continue</label>
        <label for="id_phone_number">Phone number:</label>
        <input type="text" name="phone_number" maxlength="20" id="id_phone_number" required>

        <h3 style="text-align:center;color:purple;">Add banking information</h3>
        <label for="id_account_number">Account number:</label>
        <input type="text" name="account_number" maxlength="30" id="id_account_number" required>

        <label for="id_bank_name">Bank name:</label>
        <input type="text" name="bank_name" maxlength="100" id="id_bank_name" required>

        <label for="id_ifsc_code">Ifsc code:</label>
        <input type="text" name="ifsc_code" maxlength="15" id="id_ifsc_code" required>

        <label for="id_branch">Branch:</label>
        <input type="text" name="branch" maxlength="100" id="id_branch" required>

        <label for="id_upi_id">Upi id:</label>
        <input type="text" name="upi_id" maxlength="50" id="id_upi_id" required>

        <h3 style="text-align:center;color: purple;">Add home address where the charging setup is installed<br>Its
            necessary to allow location</h3>
        <label type="submit" id="get-location" style="margin-top:3%;cursor:pointer;color:red;text-align:center;">Allow
            Location First</label>
        <label for="id_home_address">Home address:</label>
        <input type="text" name="home_address" maxlength="200" id="id_home_address" required>

        <label for="id_district">District:</label>
        <input type="text" name="district" maxlength="50" id="id_district" required>

        <label for="id_state">State:</label>
        <input type="text" name="state" maxlength="50" id="id_state" required>

        <label for="id_country">Country:</label>
        <input type="text" name="country" maxlength="50" id="id_country" required>

        <label for="id_zipcode">Zipcode:</label>
        <input type="text" name="zipcode" maxlength="10" id="id_zipcode" required>
        <input class="my" type="submit" value="Save" style="text-align:center;cursor:pointer;">
    </form>

</div>


<script>
  var getLocationButton = document.getElementById("get-location");

  getLocationButton.addEventListener("click", function() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPosition);
    } else {
      alert("Geolocation is not supported by this browser.");
    }
  });

  function showPosition(position) {
    var latitude = position.coords.latitude;
    var longitude = position.coords.longitude;

    // Send location to server using AJAX
    var xhr = new XMLHttpRequest();
    xhr.open("POST", "/getlocation/");
    xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    xhr.onreadystatechange = function() {
      if (xhr.readyState === XMLHttpRequest.DONE) {
        if (xhr.status === 200) {
          console.log(xhr.response);
        } else {
          console.log("Error:", xhr.status);
        }
      }
    };
    xhr.send(JSON.stringify({latitude: latitude, longitude: longitude}));
  }

  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }


</script>

{% endblock %}

templates/main/live.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'img/favion.png' %}" type="image/x-icon" class="favicon">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
    <style>
        .container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 1rem;
        }

        .nav__logo {
            font-size: 1rem;
            margin-top: 8px;
        }

        .map-container {
            height: 87vh;
            width: 100%;
        }
        .stop{
        display:none;
        }
    </style>
    <title>Voltage Vikings</title>
</head>
<body onload="initMap()">
<nav class="nav container" onload="updateMapWithCurrentLocation()">
    <a href="#" class="nav__logo">
        <i class="ri-steering-fill" style="font-size: 1rem;margin-top:1px;"></i>
        Voltage Vikings
    </a>
    {% if page %}
    <a  class="nav__link" onclick="homeback()">Back</a>
    {% else %}
    <a class="nav__link" onclick="stationback()">Back</a>
    {% endif %}
</nav>
<h3 id="myRoute" style="text-align:center;"></h3>
<h3 id="distance_remaining" style="text-align:center;"></h3>
<div id="map" class="map-container"></div>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTFOwZMfl--EU_d-tyIcvzA_psFSQxQDg&libraries=places&callback=initMap"></script>
<script type="text/javascript">
    var google_api_key = "{{google_api_key|safe}}";
    var origin = "{{origin|safe}}";
    var destination = "{{destination|safe}}";
    var txn_id = "{{ txn_id }}";
    var page = "{{page|safe}}";
</script>
<script>
    var src_url = "{% static "img/src1.png" %}";
    var des_url = "{% static "img/des.png" %}";
</script>
<script src="{% static 'mymap.js' %}"></script>
</body>
</html>

templates/main/nearbyhome.html
{% extends 'base.html' %}
{% block toplink %}
<li class="nav__item">
    <a href="javascript:history.go(-1)" class="nav__link">Back</a>
</li>
<li class="nav__item">
    <a href="/home" class="nav__link">Home</a>
</li>
<li class="nav__item">
    <a href="/profile" class="nav__link">Profile</a>
</li>
<li class="nav__item">
    <a href="/account/logout" class="nav__link">Logout</a>
</li>
{% endblock %}

{% block style %}
<style>
    .button {
  padding: 10;
  width: auto;
  border: 1px solid #ccc;
  font-size: 14px;
  font-weight: bold;
  text-align: center;
  cursor: pointer;
  transition: all 0.3s ease-in-out;
}
    .info1:hover {
        box-shadow: 0 10px 66px 0 purple;
    }
/* Modal sheet CSS */
.modal-sheet {
    display: none;
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.5);
    z-index: 9999;
}

.modal-sheet__content {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    background-color: #B38EC6;
    color:black;
    width: 80%;
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    border-radius: 5px;
}

.modal-sheet__title {
    font-size: 24px;
    margin-bottom: 10px;
    color:black;
}

.modal-sheet__text {
    font-size: 16px;
    margin-bottom: 20px;
     color:black;
}

.modal-sheet__button {
    padding: 10px 20px;
    background-color: #007bff;
    color: #fff;
    font-size: 16px;
    border: none;
    cursor: pointer;
}
</style>
{% endblock %}
{% block content %}
<main class="main">
    <section class="featured section" id="featured">
        <h2 class="section__title">Near By Home Charging Stations</h2>
        <div class="sort-by" style="float:right;margin-right:15%;">
            <label class="sort-by__label">Sort By Distance: </label>
            <select onchange="sort()" class="sort-by__select">
                <option value="1">1 Kms</option>
                <option value="2" selected>2 Kms</option>
                <option value="3">3 Kms</option>
                <option value="5" selected>5 Kms</option>
                <option value="10">10 Kms</option>
                <option value="15">15 Kms</option>
                <option value="25">25 Kms</option>
            </select>
        </div><br><br>
        <div class="featured__container container">
            <ul class="featured__filters">
                <a href="/nearbystations">
                    <li>
                        <button class="featured__item button" data-filter="all"
                                onclick="window.location.href='/nearbystations'">
                            <span>Charging Stations</span>
                        </button>
                    </li>
                </a>
                <a href="/nearbyhome">
                    <li>
                        <button class="featured__item button active-featured" data-filter=".tesla">
                            <span>Home Stations</span>
                        </button>
                    </li>
                </a>
            </ul>
            <div class="featured__content grid">
                {% if stat %}
                {% for i in stat %}
                <article class="featured__card mix tesla">
                    <div class="shape shape__smaller info1"></div>
                    <h1 class="featured__title">{{i.address.user.username}}</h1>
                    <h3 class="featured__subtitle">{{i.address.user.email}}</h3>
                    <h3 class="featured__subtitle">Phone: {{i.address.phone_number}}</h3>
                    <h3 class="featured__price">{{i.address.home_address}},{{i.address.district}}</h3>
                    <h3 class="featured__price">{{i.address.state}}, {{i.address.zipcode}}</h3>
                    {% if i.address.available %}
                    <button class="button featured__button" onclick="openModalSheet(this.getAttribute('data-user'))" data-user="{{i.address.id}}">
                        <i class="ri-arrow-right-line"></i>
                    </button>
                    {% else %}
                    <button class="button featured__button" disabled>
                        <i class="ri-close-line"></i>
                    </button>
                    {% endif %}
                </article>
                {% endfor %} {% else %}
           <h2 class="section__title">Not Found</h2>
            {% endif %}
            </div>
            <div class="modal-sheet" id="modalSheet">
                <div class="modal-sheet__content">
                    <h2 class="modal-sheet__title">Are you sure?</h2>
                    <p class="modal-sheet__text">We will be sending an request to user with your information.</p>
                     <input type="number" class="modal-sheet__input" id="charge" placeholder="Enter Charge Time In Minutes"
               style="display: block; width: 100%; padding: 10px; box-sizing: border-box; border: 1px solid #ccc;
            border-radius: 4px; min-width: 10; max-width: 350;" min="10" max="350"><br>
                    <button class="modal-sheet__button" id="yesButton">YES</button>
                    <br>
                    <button class="modal-sheet__button" onclick="closeModalSheet()">NO</button>
                </div>
            </div>
        </div>
    </section>
</main>
{% block script %}
<script>
function openModalSheet(to_id) {
    document.getElementById('modalSheet').style.display = 'block';
    const yesButton = document.getElementById("yesButton");
    const time = document.getElementById("charge");
    yesButton.addEventListener("click", function() {
    var charge_time = time.value;
    closeModalSheet();
    send(charge_time, to_id);
    });
}
function closeModalSheet() {
    document.getElementById('modalSheet').style.display = 'none';
}
function send(charge_time, to_id){
   document.getElementById('modalSheet').style.display = 'none';
   var conf = confirm("We are sending now? Are you sure!!");
   if(conf){
              var xhr = new XMLHttpRequest();
              xhr.open("POST", "/send_request/");
              xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
              xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
              xhr.onreadystatechange = function() {
                if (xhr.readyState === XMLHttpRequest.DONE) {
                  if (xhr.status === 200) {
                     window.alert("Request Sent Sucessfully!!\nKindly Wait For 5 Minutes\nCheck Out Your Request Section!!");
                  }if (xhr.status === 400) {
            var response = JSON.parse(xhr.responseText);
            window.alert(response.message);
        }
                }
              };
              xhr.send(JSON.stringify({
                charge_time: charge_time,
                to_id : to_id,
              }));
}
}
function sort() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(sort_dist);
    } else {
      alert("Geolocation is not supported by this browser.");
    }
}
function sort_dist(position){
 var latitude = position.coords.latitude;
    var longitude = position.coords.longitude;
const sortSelect = document.querySelector('.sort-by__select');
const selectedValue = sortSelect.value;
var xhr = new XMLHttpRequest();
xhr.open("POST", "/nearbyhome/");
xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
xhr.onreadystatechange = function() {
  if (xhr.readyState === XMLHttpRequest.DONE) {
    if (xhr.status === 200) {
          document.body.innerHTML = xhr.responseText;
          var sortSelect = document.querySelector('.sort-by__select');
          sortSelect.value = selectedValue;
    } else {
      console.log("Error:", xhr.status);
    }
  }
};
xhr.send(JSON.stringify({latitude: latitude, longitude: longitude, dest_got: selectedValue}));
}
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
</script>
{% endblock %}
{% endblock %}

templates/main/profile.html
{% extends 'base.html' %}
{% block toplink %}
<li class="nav__item">
    <a href="/home" class="nav__link">Home</a>
</li>
<li class="nav__item">
    <a href="/account/logout" class="nav__link">Logout</a>
</li>
{% endblock %}
{% block style %}
<style>
.container1 {
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f7f7f7;
    border: 1px solid purple;
    border-radius: 10px;
    margin-top:10%;
}
h1 {
    text-align: center;
    margin-top: 0;
    color: purple;
}
form {
    margin-top: 20px;
}
label, input {
    display: block;
    margin-bottom: 10px;
    width: 100%;
    color:black;
}
input {
    padding:10px;
    border: 1px solid purple;
    }
input[type="submit"] {
    background-color: #007bff;
    color: #fff;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
    transition: background-color 0.3s ease;
}
input[type="submit"]:hover {
    background-color: #0056b3;
}
#validation-msg {
    text-align: center;
    color: red;
    margin-top: 10px;
    font-size: 14px;
}
@media screen and (max-width: 768px) {
    .container1 {
        max-width: 100%;
        margin: 0;
        padding: 10px;
        margin-top:20%;
    }
}
</style>
{% endblock %}
{% block content %}
    <div class="container1">
        {% if err %}
        <h1>{{err}}</h1>
        {% else %}
        <h1>Profile And Settings</h1>
        <form method="post" action="/profile/">
        {% csrf_token %}
        <h1 style="color: purple;">Your profile</h1>
        <label for="ph">User Name:</label>
        <input type="text" id="ph" name="uname" value="{{user.username}}" required disabled>
        <label for="email">User Email:</label>
        <input type="text" id="email" name="email" value="{{user.email}}" required disabled>
        <label for="password">User Password:</label>
        <input type="text" id="password" name="pass" value="*************" required disabled>
        <label style="color:red;text-align:right;cursor:pointer;"><a href="/account/password/change/">Change Password</a></label>
        {% if data.completed_profile %}
        <label for="email">Wallet Balance:</label>
        <input type="text" id="wallet" name="email" value="{{data.wallet}}" required disabled>
         <label style="color:red;text-align:right;cursor:pointer;"><a href="#">Withdraw</a></label>
        <label for="id_phone_number">Phone Number:</label>
        <input type="text" id="id_phone_number" name="phone_number"  maxlength="20" value="{{data.phone_number}}" required disabled>
        <label style="color:red;text-align:center;">Banking Information</label>
        <label for="id_account_number">Account Number:</label>
        <input type="text" id="id_account_number" name="account_number" maxlength="30"  value="{{data.account_number}}" required disabled>
        <label for="id_bank_name">Bank Name:</label>
        <input type="text" id="id_bank_name" name="bank_name" maxlength="100" value="{{data.bank_name}}" required disabled>
        <label for="id_ifsc_code">IFSC Code:</label>
        <input type="text" id="id_ifsc_code" name="ifsc_code" maxlength="15" value="{{data.ifsc_code}}" required disabled>
        <label for="id_branch">Branch:</label>
        <input type="text" id="id_branch" name="branch" value="{{data.branch}}" maxlength="100" required disabled>
        <label for="id_upi_id">UPI ID:</label>
        <input type="text" id="id_upi_id" name="upi_id" value="{{data.upi_id}}" maxlength="50" required disabled>
          <label style="color:red;text-align:center;">Home address where the charging setup is installed</label>
        </label>
        {% if not data.got_loc %}<label style="color:red;text-align:center;">Its
            necessary to allow location</label>
            <label style="color:purple;text-align:right;cursor:pointer;" id="get-location">Allow Location First</label>
            {% endif %}
        <label for="id_home_address">Address:</label>
        <input type="text" id="id_home_address" name="home_address" value="{{data.home_address}}" maxlength="200" required disabled>
        <label for="id_district">District:</label>
        <input type="text" id="id_district" name="district" value="{{data.district}}" maxlength="50"  required disabled>
        <label for="id_state">State:</label>
        <input type="text" name="state" value="{{data.state}}" id="id_state" maxlength="50" required disabled>
        <label for="id_country">Country:</label>
        <input type="text" id="id_country" name="country" value="{{data.country}}" maxlength="50"  required disabled>
        <label for="id_zipcode">Zipcode:</label>
        <input type="text" value="{{data.zipcode}}" name="zipcode" maxlength="10" id="id_zipcode" required disabled>
        <input class="my" id="editBtn" value="Edit" style="text-align:center;cursor:pointer;">
        <input class="my" value="Save"  id="saveBtn" style="display:none;text-align:center;cursor:pointer;">
        <input type="submit" class="my" value="Make Changes" style="display:none;"  id="makechanges" step="cursor:pointer;">
    </form>
            {% else %}<br>
         <a href="/completeprofile" ><h3 style="text-align:center;color:red;">Upadate Profile Now!</h3></a>
        {% endif %}
    {% endif %}
    </div>
<script>
  var getLocationButton = document.getElementById("get-location");
  getLocationButton.addEventListener("click", function() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPosition);
    } else {
      alert("Geolocation is not supported by this browser.");
    }
  });
  function showPosition(position) {
    var latitude = position.coords.latitude;
    var longitude = position.coords.longitude;
    var xhr = new XMLHttpRequest();
    xhr.open("POST", "/getlocation/");
    xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    xhr.onreadystatechange = function() {
      if (xhr.readyState === XMLHttpRequest.DONE) {
        if (xhr.status === 200) {
         window.location.reload();
        } else {
          console.log("Error:", xhr.status);
        }
      }
    };
    xhr.send(JSON.stringify({latitude: latitude, longitude: longitude}));
  }
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
</script>
<script>
const phone = document.getElementById('id_phone_number');
const acc_no = document.getElementById('id_account_number');
const bank_name = document.getElementById('id_bank_name');
const ifsc = document.getElementById('id_ifsc_code');
const branch = document.getElementById('id_branch');
const upi = document.getElementById('id_upi_id');
const address = document.getElementById('id_home_address');
const dist = document.getElementById('id_district');
const state = document.getElementById('id_state');
const country = document.getElementById('id_country');
const zipcode = document.getElementById('id_zipcode');
const editBtn = document.getElementById('editBtn');
const saveBtn = document.getElementById('saveBtn');
const makechanges = document.getElementById('makechanges');
editBtn.addEventListener('click', () => {
 editBtn.style.display = 'none';
  editBtn.disabled = true;
  phone.disabled = false;
  acc_no.disabled = false;
  bank_name.disabled = false;
  ifsc.disabled = false;
  branch.disabled = false;
  upi.disabled = false;
  address.disabled = false;
  dist.disabled = false;
  state.disabled = false;
  country.disabled = false;
  zipcode.disabled = false;
  saveBtn.style.display = 'block';
});
saveBtn.addEventListener('click', () => {
  saveBtn.style.display = 'none';
  makechanges.style.display = 'block';
});
</script>
{% endblock %}